services:

  JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\HasNodeTransitionRegistryDecorator:
    class: JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\HasNodeTransitionRegistryDecorator
    arguments:
      - '@JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\HasNodeTransitionRegistryDecorator.inner'
    lazy: true

  JobBoy\Flow\Domain\FlowManager\TransitionRegistry:
    class: JobBoy\Flow\Domain\FlowManager\TransitionRegistry
    lazy: true
