services:

  JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\BundleTransitionRegistryAdapter:
    class: JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\BundleTransitionRegistryAdapter
    arguments:
      - '@JobBoy\Flow\Domain\FlowManager\TransitionRegistry'
    lazy: true

  JobBoy\Flow\Domain\FlowManager\TransitionRegistry:
    class: JobBoy\Flow\Domain\FlowManager\TransitionRegistry
    lazy: true
