services:

  JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\BundleTransitionRegistryDecorator:
    class: JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\BundleTransitionRegistryDecorator
    arguments:
      - '@JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\BundleTransitionRegistryDecorator.inner'
    decorates: JobBoy\Flow\Domain\FlowManager\TransitionRegistry
    lazy: true

  JobBoy\Flow\Domain\FlowManager\TransitionRegistry:
    class: JobBoy\Flow\Domain\FlowManager\TransitionRegistry
    lazy: true
