services:

  JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\TransitionLoader\BundleTransitionLoaderAdapter:
    class: JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\TransitionLoader\BundleTransitionLoaderAdapter
    arguments:
      - '@JobBoy\Flow\Domain\FlowManager\TransitionLoader'
    lazy: true


  JobBoy\Flow\Domain\FlowManager\TransitionLoader:
    class: JobBoy\Flow\Domain\FlowManager\TransitionLoader\TransitionLoader
    arguments:
      - '@JobBoy\Flow\Domain\FlowManager\TransitionRegistry'
    lazy: true


