services:

  JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\TransitionLoader\BundleTransitionLoaderDecorator:
    class: JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\TransitionLoader\BundleTransitionLoaderDecorator
    arguments:
      - '@JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\TransitionLoader\BundleTransitionLoaderDecorator.inner'
    decorates: JobBoy\Flow\Domain\FlowManager\TransitionLoader
    lazy: true


  JobBoy\Flow\Domain\FlowManager\TransitionLoader:
    class: JobBoy\Flow\Domain\FlowManager\TransitionLoader\TransitionLoader
    arguments:
      - '@JobBoy\Flow\Domain\FlowManager\TransitionRegistry'
    lazy: true

