services:

  JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\TransitionLoader\RegisterTransitionSetProvidersTransitionLoaderDecorator:
    class: JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\TransitionLoader\RegisterTransitionSetProvidersTransitionLoaderDecorator
    arguments:
      - '@JobBoy\Bundle\JobBoyBundle\Flow\Domain\FlowManager\TransitionLoader\RegisterTransitionSetProvidersTransitionLoaderDecorator.inner'
    decorates: JobBoy\Flow\Domain\FlowManager\TransitionLoader

  JobBoy\Flow\Domain\FlowManager\DefaultTransitionLoader:
    class: JobBoy\Flow\Domain\FlowManager\TransitionLoader\DefaultTransitionLoader
    arguments:
      - '@JobBoy\Flow\Domain\FlowManager\TransitionRegistry'

  JobBoy\Flow\Domain\FlowManager\TransitionLoader:
    alias: JobBoy\Flow\Domain\FlowManager\DefaultTransitionLoader
