services:

  JobBoy\Flow\Domain\FlowManager\TransitionLoader:
    class: JobBoy\Flow\Domain\FlowManager\TransitionLoader\TransitionLoader
    arguments:
      - '@JobBoy\Flow\Domain\FlowManager\TransitionRegistry'
    lazy: true
