services:

  JobBoy\Process\Domain\PauseControl\PauseControl:
    alias: JobBoy\Process\Domain\PauseControl\Infrastructure\File\PauseControl

  JobBoy\Process\Domain\PauseControl\Infrastructure\File\PauseControl:
    class: JobBoy\Process\Domain\PauseControl\Infrastructure\File\PauseControl