services:

  JobBoy\Process\Domain\Jobs\Dummy\ProcessHandlers\Initialize:
    class: JobBoy\Process\Domain\Jobs\Dummy\ProcessHandlers\Initialize
    arguments:
      - "@JobBoy\Process\Domain\Repository\ProcessRepositoryInterface"
    lazy: true
    tags:
      - name: jobboy.process_handler

  JobBoy\Process\Domain\Jobs\Dummy\ProcessHandlers\Iterate:
    class: JobBoy\Process\Domain\Jobs\Dummy\ProcessHandlers\Iterate
    arguments:
      - "@JobBoy\Process\Domain\Repository\ProcessRepositoryInterface"
    lazy: true
    tags:
      - name: jobboy.process_handler


  JobBoy\Process\Domain\Jobs\Dummy\ProcessHandlers\FreeHandled:
    class:   JobBoy\Process\Domain\Jobs\Dummy\ProcessHandlers\FreeHandled
    arguments:
      - "@JobBoy\Process\Domain\Repository\ProcessRepositoryInterface"
    lazy: true
    tags:
      - name: jobboy.process_handler
        priority: 101

  JobBoy\Process\Domain\Jobs\Dummy\ProcessHandlers\ResolveMissingCases:
    class: JobBoy\Process\Domain\Jobs\Dummy\ProcessHandlers\ResolveMissingCases
    arguments:
      - "@JobBoy\Process\Domain\Repository\ProcessRepositoryInterface"
    lazy: true
    tags:
      - name: jobboy.process_handler
        priority: 102

