services:

  JobBoy\Bundle\JobBoyBundle\Step\Domain\StepManager\HasStepDataStepRegistryDecorator:
    class: JobBoy\Bundle\JobBoyBundle\Step\Domain\StepManager\HasStepDataStepRegistryDecorator
    arguments:
      - '@JobBoy\Bundle\JobBoyBundle\Step\Domain\StepManager\HasStepDataStepRegistryDecorator.inner'
    decorates: JobBoy\Step\Domain\StepManager\StepRegistry
    lazy: true

  JobBoy\Step\Domain\StepManager\StepRegistry:
    class: JobBoy\Step\Domain\StepManager\StepRegistry
    lazy: true



